title: Your awesome title
email: your-email@example.com
baseurl: ""
url: ""

twitter_username: jekyllrb
github_username:  jekyll
name: Kevin F. Grant Jr. 
github: FNebEx

# API Key's
snipcart: ZmRhMGM3ZTctM2YwNS00ZmUwLWIzMTYtNjhiNjBlMzNmY2FlNjM2OTI0MDk4MzQ4NTQ1ODYx
formsapi: might not even use.

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  albums:
    output: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
  - scope:
      path: ""
      type: "albums"
      permalink: /:collection/:name
    values:
      layout: "item_page"
      price: 9
      sold_out: false


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
