---
title: Your awesome title
url: https://grantkf01.netlify.com
timezone: UTC
collections:
  albums:
    title: Albums
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
    path: ''
    type: albums
  values:
    layout: item_page
    price: 9
    sold_out: false
email: your-email@example.com
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
name: Kevin F. Grant Jr.
github: FNebEx
snipcart: ZmRhMGM3ZTctM2YwNS00ZmUwLWIzMTYtNjhiNjBlMzNmY2FlNjM2OTI0MDk4MzQ4NTQ1ODYx
formsapi: might not even use.
markdown: kramdown
plugins:
- jekyll-feed
